<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

require '../Database/config.php';

// Only accept post payloads
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method Not Allowed']);
    exit;
}

$data = json_decode(file_get_contents("php://input"), true);

if (!isset($data['cart']) || empty($data['cart'])) {
    echo json_encode([
        'success' => false,
        'message' => 'Cart data is missing or empty'
    ]);
    exit;
}

$paymentMethod  = $data['payment_method'] ?? 'Cash';
$discountAmount = floatval($data['discount_amount'] ?? 0);

$totalAmount    = floatval($data['total_amount'] ?? 0);

try {
    $pdo->beginTransaction();

    // 1. GENERATE THE SEQUENTIAL ORDER NUMBER (e.g., 0001, 0002)
    $countStmt = $pdo->query('SELECT COUNT(*) FROM orders');
    $nextNumber = $countStmt->fetchColumn() + 1;
    $orderNo = str_pad($nextNumber, 4, '0', STR_PAD_LEFT);

    // 2. INSERT SUMMARY INTO THE PARENT 'orders' TABLE
    $orderSql = 'INSERT INTO orders (order_no, total_amount, discount_amount, payment_method) VALUES (?, ?, ?, ?)';
    $orderStmt = $pdo->prepare($orderSql);
    $orderStmt->execute([$orderNo, $totalAmount, $discountAmount, $paymentMethod]);

    // Capture the primary ID generated by auto-increment for this order
    $orderId = $pdo->lastInsertId();

    // Prepare line item insert statement outside the loop for optimization
    $itemSql = 'INSERT INTO order_items (order_id, product_id, quantity, price_at_sale) VALUES (?, ?, ?, ?)';
    $itemStmt = $pdo->prepare($itemSql);

    // 3. LOOP THROUGH CART FOR STOCK DEDUCTION AND LINE-ITEM ENTRIES
    foreach ($data['cart'] as $item) {
        $id    = intval($item['id']);
        $qty   = intval($item['qty']);
        $price = floatval($item['price']); // Capture item base unit price metric context

        // Check current stock levels dynamically
        $stmt = $pdo->prepare("SELECT stock, name FROM products WHERE id = ?");
        $stmt->execute([$id]);
        $product = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$product) {
            throw new Exception("Product code ID " . $id . " could not be found in active catalogs.");
        }

        if ($product['stock'] < $qty) {
            throw new Exception("Insufficient stock parameters tracking for item: " . $product['name']);
        }

        // A. Deduct stock from the 'products' table
        $update = $pdo->prepare("UPDATE products SET stock = stock - ? WHERE id = ?");
        $update->execute([$qty, $id]);

        // B. Log specific product sales line trace link within 'order_items'
        $itemStmt->execute([$orderId, $id, $qty, $price]);
    }

    // Commits all transaction modifications safely to database engine partitions simultaneously
    $pdo->commit();

    echo json_encode([
        'success'  => true,
        'order_no' => $orderNo,
        'message'  => 'Transaction completed and logged successfully.'
    ]);
} catch (Exception $e) {
    // Reverts structural impacts clean if exceptions interrupt loop chains execution
    $pdo->rollBack();

    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
