<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

require '../Database/config.php';

// Only accept post payloads
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method Not Allowed']);
    exit;
}

$data = json_decode(file_get_contents("php://input"), true);

if (!isset($data['cart']) || empty($data['cart'])) {
    echo json_encode([
        'success' => false,
        'message' => 'Cart data is missing or empty'
    ]);
    exit;
}

$paymentMethod  = $data['payment_method'] ?? 'Cash';
$discountAmount = floatval($data['discount_amount'] ?? 0);
$totalAmount    = floatval($data['total_amount'] ?? 0);

// 🌟 NEW: Extract Cash Received and Change Amount parameters from data payload
$cashReceived   = floatval($data['cash_received'] ?? 0);
$changeAmount   = floatval($data['change_amount'] ?? 0);

try {
    $pdo->beginTransaction();

    // 1. GENERATE THE SEQUENTIAL ORDER NUMBER (e.g., 0001, 0002)
    $countStmt = $pdo->query('SELECT COUNT(*) FROM orders');
    $nextNumber = $countStmt->fetchColumn() + 1;
    $orderNo = str_pad($nextNumber, 4, '0', STR_PAD_LEFT);

    // 2. INSERT SUMMARY INTO THE PARENT 'orders' TABLE
    // 🌟 UPDATED: Added cash_received and change_amount columns to query line
    $orderSql = 'INSERT INTO orders (order_no, total_amount, discount_amount, payment_method, cash_received, change_amount) VALUES (?, ?, ?, ?, ?, ?)';
    $orderStmt = $pdo->prepare($orderSql);
    $orderStmt->execute([$orderNo, $totalAmount, $discountAmount, $paymentMethod, $cashReceived, $changeAmount]);

    // Capture the primary ID generated by auto-increment for this order
    $orderId = $pdo->lastInsertId();

    // Prepare line item insert statement outside the loop for optimization
    $itemSql = 'INSERT INTO order_items (order_id, product_id, quantity, price_at_sale) VALUES (?, ?, ?, ?)';
    $itemStmt = $pdo->prepare($itemSql);

    // 3. LOOP THROUGH CART FOR STOCK DEDUCTION AND LINE-ITEM ENTRIES
    foreach ($data['cart'] as $item) {
        $id    = intval($item['id']);
        $qty   = intval($item['qty']);
        $price = floatval($item['price']);

        // Check current total stock levels dynamically
        $stmt = $pdo->prepare("SELECT stock, name FROM products WHERE id = ?");
        $stmt->execute([$id]);
        $product = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$product) {
            throw new Exception("Product code ID " . $id . " could not be found in active catalogs.");
        }

        if ($product['stock'] < $qty) {
            throw new Exception("Insufficient stock parameters tracking for item: " . $product['name']);
        }

        // --- NEW FIFO LOGIC: Deduct from oldest available batches first ---
        $batchStmt = $pdo->prepare("
            SELECT id, quantity_remaining 
            FROM product_batches 
            WHERE product_id = ? AND quantity_remaining > 0
            ORDER BY created_at ASC
        ");
        $batchStmt->execute([$id]);
        $batches = $batchStmt->fetchAll(PDO::FETCH_ASSOC);

        $remainingToDeduct = $qty;

        foreach ($batches as $batch) {
            if ($remainingToDeduct <= 0) break;

            $batchId = $batch['id'];
            $currentBatchStock = $batch['quantity_remaining'];

            if ($currentBatchStock >= $remainingToDeduct) {
                // This batch can fully satisfy the remaining order amount
                $newBatchStock = $currentBatchStock - $remainingToDeduct;
                $updateBatch = $pdo->prepare("UPDATE product_batches SET quantity_remaining = ? WHERE id = ?");
                $updateBatch->execute([$newBatchStock, $batchId]);
                $remainingToDeduct = 0;
            } else {
                // Wipe out this batch to 0, deduct what we can, and move to the next batch
                $remainingToDeduct -= $currentBatchStock;
                $updateBatch = $pdo->prepare("UPDATE product_batches SET quantity_remaining = 0 WHERE id = ?");
                $updateBatch->execute([$batchId]);
            }
        }

        // Fallback check if batches didn't correctly sync with the total stock field
        if ($remainingToDeduct > 0) {
            throw new Exception("FIFO Error: Batches for '" . $product['name'] . "' are desynced with total stock.");
        }

        // A. Synchronize total structural stock cache in the 'products' table
        $updateProductsTable = $pdo->prepare("
            UPDATE products 
            SET stock = (SELECT COALESCE(SUM(quantity_remaining), 0) FROM product_batches WHERE product_id = ?) 
            WHERE id = ?
        ");
        $updateProductsTable->execute([$id, $id]);

        // B. Log specific product sales line trace link within 'order_items'
        $itemStmt->execute([$orderId, $id, $qty, $price]);
    }

    // Commits all transaction modifications safely to database engine partitions simultaneously
    $pdo->commit();

    echo json_encode([
        'success'  => true,
        'order_no' => $orderNo,
        'message'  => 'Transaction completed and logged successfully.'
    ]);
} catch (Exception $e) {
    // Reverts structural impacts clean if exceptions interrupt loop chains execution
    $pdo->rollBack();

    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
